[package]
name = "minivpn"
version = "0.1.0"
edition = "2021"

[dependencies]
tun = "0.5.5"
socket2 = {version="0.5.3", features=["all"]}
packet = "0.1.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
